# Generated by Django 5.0.4 on 2024-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words_in_note',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='words_in_note',
            field=models.IntegerField(default=0),
        ),
    ]
